version: '3.1'

services:
    mysql:
      container_name: test-db
      image: mysql:latest
      volumes:
        - ./mysql/conf:/etc/conf.d
        - ./mysql/init:/docker-entrypoint-initdb.d
      environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_DATABASE=test-db"
      ports:
        - "3306:3306"
