version: '3.1'

services:
    mysql:
      image: mysql:latest
      volumes:
        - ./mysql/my.cnf:/etc/my.cnf
        - ./mysql/init:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=mysql
      ports:
        - "3306:3306"

    canal:
      image: canal/canal-server
      environment:
        - canal.instance.master.address=mysql:3306
        - canal.instance.dbUsername=canal
        - canal.instance.dbPassword=canal
        - canal.instance.connectionCharset=UTF-8
        - canal.instance.tsdb.enable=true
        - canal.instance.gtidon=false
#        - canal.instance.filter.regex=.*\\..*
        - canal.auto.scan=false
        - canal.destinations=example
      ports:
        - "11111:11111"
      depends_on:
        - mysql
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
    kafka:
      image: wurstmeister/kafka
      ports:
        - "9092"
      environment:
        DOCKER_API_VERSION: 1.22
        KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      volumes:
#        - /var/run/docker.sock:/var/run/docker.sock

    es:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
      ports:
        - "9200:9200"
        - "9300:9300"

      environment:
        discovery.type: single-node

    kibana:
      image: docker.elastic.co/kibana/kibana:7.14.0
      ports:
        - "5601:5601"
      environment:
        - ELASTICSEARCH_HOSTS=http://es:9200
      depends_on:
        - es